proxy:
  port: 8080
  openid:
    auth-url: https://realtyquant.auth0.com/authorize
    token-url: https://realtyquant.auth0.com/oauth/token
    jwks-url: https://realtyquant.auth0.com/.well-known/jwks.json
    client-id: OhTgbMLTkWT29nUjSjUHFt0MeXqOqnOo
    client-secret: ufm5xskzakDL4iDzSGCfE54fLK01J62h6tjT0tZ1FQrN4rb4sG3APOfoked8CFrP
  docker:
    url: http://localhost:2375
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo

logging:
  file:
    shinyproxy.log